name: flutter_assignment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^11.0.0
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  build_runner: ^2.4.6
  freezed:
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  intl_utils: ^2.8.4
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  flutter_login_facebook: ^1.8.0
  linkedin_login: ^2.3.1
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true
  main_locale: en
